name: Vercel PR Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  pr-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Deploy Project Artifacts to Vercel
        run: npx vercel@latest deploy --token=$VERCEL_TOKEN --cwd=frontend --prebuilt
