name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
on:
  push:
    branches:
      - main
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install Dependencies
        run: npm install --prefix frontend

      - name: Deploy Project Artifacts to Vercel
        run: npx vercel@latest deploy --prod --token=$VERCEL_TOKEN --cwd=frontend --env DATABASE_URL=${{ secrets.DATABASE_URL }}
